export enum Continent {
  AFRICA = 'AFRICA',
  ANTARCTICA = 'ANTARCTICA',
  ASIA = 'ASIA',
  AUSTRALASIA = 'AUSTRALASIA',
  EUROPE = 'EUROPE',
  NORTHAMERICA = 'NORTHAMERICA',
  SOUTHAMERICA = 'SOUTHAMERICA',
}
